### ISSUE TITLE
Ctrl-l shortcut already assigned to Core's select line

### ISSUE THREAD

**Issue by joshstar** [vishysank/console-log-atom#1]
Just installed this package and tried it out but found that ctrl-l was already bound to Atom Core's editor:select-line. I had to rebind console-log to ctrl-alt-l to get it to work.

Maybe change the key binding of this package to something else by default?

**Comment by vishysank** [comment]
ah, I assume you are using a windows computer. In macs there is a cmd button and cmd-l is the binding for editor:select-line. I shall push a patch out that adds a ctrl-alt-l binding so that windows users can use this effectively as well. Keep a lookout for the patch update soon.

Thanks for bring this up.

**Comment by vishysank** [comment]
@Josh-Star this has now been fixed v0.3.1. For linux/windows users the key `ctrl-alt-l` should also work now.
