### ISSUE TITLE
Cannot disable "CONDITION PASSED" message

### ISSUE THREAD

**Issue by pdonias** [vishysank/console-log-atom#23]
1. Uncheck "Condition Passed Message" in the settings
2. Select an `if` condition
3. `Console Log: Add`

Result:
```js
console.log('condition', condition)
if (condition) {
  console.log('CONDITION PASSED')
  // do something
}
```

Isn't `console.log('CONDITION PASSED')` not supposed to show? Am I missing something? :confused:

Atom: 1.13.1
console-log: 1.9.0

**Comment by vishysank** [comment]
hey @pdonias, long time no see 😄.

I think I wrote down why this works this way in the docs check it out and let me know your thoughts.

Smart Conditionals Logging (early release)

if a variable used in a definition of the conditional in an if statement is logged, the insert is placed on the line above the if statement and a 'CONDITION PASSED' insert in the if statement, so that the logging is not lost if the condition doesn't pass, and there is clear validation if the condition passed. For subsequent chained conditionals, insert is placed within the conditional.

**Comment by pdonias** [comment]
I understand the feature and I think it's great! :)
But I was actually trying to disable it by unchecking the box in the package config:
![capture du 2017-02-02 09-39-21](https://cloud.githubusercontent.com/assets/10992860/22542395/de284836-e92b-11e6-94d2-ac59c1ded00b.png)

But after a quick research, I actually can't find this config option in the code!
So what? Am I seeing ghost options?? :laughing:

At first, I thought that it was me who added the option some time ago and that I was loading the dev package by mistake, but it doesn't seem to be the case.
So I really don't understand what's happening.

Anyway, if you can confirm that such an option is not supposed to exist, you can close the issue since the feature is working as it's supposed to.
And then I'll try to understand where the ghost option comes from...

**Comment by vishysank** [comment]
yeah i dont see this option. Maybe try reinstalling the application, it might be a hold over thing. I'm going to close this in the meantime.

Thanks for logging though !
